### ISSUE TITLE
Unable to send HTTP 500 (instead of HTTP 401) in case of custom authentication error 

### ISSUE THREAD

**Issue by gyszalai** [http-auth/http-auth#65]
Hi!

I use custom authentication with http-auth. I call a 3rd party authentication 
service to check if a given user and password is correct, like this:

```javascript
    const basicAuth = auth.basic({
            msg401: JSON.stringify({error: 'invalid_client'}),
            contentType: 'application/json'
        },
        function (username, password, callback) {
            clientAuthService
                .authenticate(username, password)
                .then(authenticated => {
                    callback(authenticated)
                })
                .catch(error => {
                    callback(false) //FIXME: throw error
                })

        }
    )
```
The authentication is used for protecting an express route:
```javascript
    router.route('/dummy').post(
        auth.connect(basicAuth), // HTTP Basic auth
        function(req, res) {
            ....
        }
    )
```

My problem is that the callback accepts only a boolean, that tells whether 
the user is authenticated or not. There is no way to signal that there was an error
so that the client should get an HTTP 500 response instead of HTTP 401.

I tried to rethrow the error, but in that case no response was sent to the client.
How can I solve this?

**Comment by gevorg** [comment]
Hi! Ideally I think server should never have an expected case that will throw 50x error, but I got your point and will answer during 24 hours. 

Before my answer could you please make sure you have proper exception handling for express http://expressjs.com/en/guide/error-handling.html

I assume you can return any response in exception handler and ignore `callback` call, by rethrowing it.

**Comment by gyszalai** [comment]
Hi!

I set up a global error handler for my express app like this:
```javascript
app.use(function(err, req, res, next) {  // eslint-disable-line no-unused-vars
    console.error('Error', err.stack)
    res.status(500).json({reason: 'Server error'})
})
```
so, in theory, all uncatched exception would cause an HTTP 500 response.

**Comment by gevorg** [comment]
Hi!

I was hiding exceptions somewhere in my module and that is the reason why you didn't get expected result in error handler.

I fixed issue with `2.3.7` version and published to `npm`.
Following code snippet should work now:

``` javascript
// Authentication module.
var auth = require('http-auth');
var basic = auth.basic({
    realm: "Simon Area."
}, function (username, password, callback) {
    throw new Error("Some odd error");
});

// Application setup.
var app = require('express')();

// Setup route.
app.get('/', auth.connect(basic), function(req, res) {
    res.send("Hello from express - " + req.user + "!");
});

// Error handler.
app.use(function(err, req, res, next) {
    console.error('Error', err.stack);
    res.status(500).json({reason: 'Server error'})
});

// Start server.
app.listen(1337, function () {
    // Log URL.
    console.log("Server running at http://127.0.0.1:1337/");
});

```

Thanks for reporting!

**Comment by gyszalai** [comment]
Thanks for the quick fix, but for my case it still doesn't work.
This solution works if the checker callback directly throws an Error.

In my case there is async code in the checker callback:
`clientAuthService.authenticate(username, password)` 
returns a Promise, which is rejected if there was an error. 

Is there any way to send back http 500 in this case? It would be important 
to the client to know that there was a server error and the problem was 
not on their side. HTTP 401 is a client error.

**Comment by gevorg** [comment]
Done with `2.3.8` version and published to `npm`, something like this works for me

```javascript
var basic = auth.basic({
    realm: "Simon Area."
}, function (username, password, callback) {
    setTimeout(function () {
        callback(new Error("Some odd error"));
    }, 100);
});

```

**Comment by gyszalai** [comment]
Thanks for the quick fix again!
